resource_group_name = "devrg"
resource_group_location = "East US"
mssqlservername = "devsldatabse01server"
mssqlversion = "12.0"
mssqllogin = "sqladmin"
mssqlpassword = "Azure@123456"
publicnetworkaccessenabled = true
mssqldatabasename = "devsldatabse01"
collation = "SQL_Latin1_General_CP1_CI_AS"
size = 250
skuname = "S0"
